### ISSUE TITLE
Weatherflow station with UDP drivers causes NULL values to appear in the realtime file

### ISSUE THREAD

**Issue by Hyrules** [matthewwall/weewx-crt#5]
When you connect a weatherflow weather station (like the tempest) by using the UDP driver to weewx the station sends a few types of packets which are not all observations.

Every 3 seconds the station sends a wind reading that also contains a few other observations
{'dateTime': 1596830467, 'windSpeed': 2.3935277815750555, 'windDir': 109, 'usUnits': 1, 'beaufort': 1, 'maxSolarRad': 665.1178206717788, 'rainRate': 0.0}

Every 60 seconds a complete observation is sent from the station.
{'dateTime': 1596830473, 'outTemp': 80.726, 'outHumidity': 43.94, 'pressure': 29.937796627375, 'lightning_strike_count': 0, 'lightning_avg_distance': 0, 'outTempBatteryStatus': 2.768, 'UV': 4.53, 'rain': 0.0, 'windBatteryStatus': 2.768, 'radiation': 867, 'pcpt_type': 0, 'illuminance': 104061, 'usUnits': 1, 'altimeter': 30.322237320383994, 'barometer': 30.30465002645203, 'cloudbase': 5806.684634034163, 'dewpoint': 56.72121087195945, 'heatindex': 80.8244986804421, 'humidex': 86.5052294161618, 'maxSolarRad': 664.8613565480847, 'rainRate': 0.0}

There are other packets type which are irrelevant here. If you set weewx-crt binding to archive everything is fine but if you let it by default the realtime file is incomplete with alot of null values which end up appearing in the program that uses the realtime file.  This is an issue because it's not really a realtime observation but rather a delayed one. You have to wait for the archive loop to have a valid reading. Luckily the archive packed is send on a minute basis which is not that long but meanwhile you miss other realtime values like wind and rain rate.

This happens on the latest Weewx 4.1.1. It would be interesting to see this issue fixed. Thanks.

**Comment by europacafe** [comment]
It would be nice if the crt-extension, when receiving the "every-3-second" reading, it should fill up the other fields in realtime.txt with the latest "every-60-second" data.

**Comment by msman0** [comment]
Hi, is there any possibility to fix the problem?

**Comment by matthewwall** [comment]
i think this is not an issue with weewx-crt, but with whatever is using weewx-crt data.

a fundamental principle in weewx is that we do not fabricate data.  a related principle is that we avoid caching data whenever possible.

if weewx-crt were stateful, then it is no longer real-time - it would be caching data, then trying to figure out when to update caches, and having to understand any relationships between cached observations.

it is the responsibility of the data consumer downstream of weewx-crt to realize that a NULL only means there is no information, and update its display only for data that are non-NULL.
