### ISSUE TITLE
Wind direction should not be blank even wind speed is zero, in realtime.txt file

### ISSUE THREAD

**Issue by europacafe** [matthewwall/weewx-crt#6]
The wind direction in realtime.txt is shown as --- when wind speed is zero. In some circumstances, where wind direction changes due to minute wind speed; but the wind cups may not rotate (due to very minute wind or the wind cup itself has a problem rotating). The realtime.txt should still report wind direction in such circumstances.
Thank you

**Comment by matthewwall** [comment]
i think this is a weewx issue, not weewx-crt issue.  in weewx, when wind speed is zero, wind direction is undefined, thus `---`.  there is option in weewx configuration to change this behavior.
